vich_uploader:
    db_driver: orm

    mappings:
        bien_image:
            uri_prefix: /images/biens
            upload_destination: '%kernel.project_dir%/public/images/biens'
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # inject_on_load:     true
            # delete_on_update:   true
            # delete_on_remove:   true
            

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
